import {
  Cat,
  Dog,
  Bird,
  Fish,
  Rabbit,
  Snail,
  Bug,
  Flame,
  Zap,
  Star,
  Moon,
  Sun,
  Heart,
  Skull,
  Ghost,
  Rocket,
  Crown,
  Gem,
  Anchor,
  Gamepad2,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { PlayerIcon } from "../../shared/types.ts";

export const ICON_MAP: Record<PlayerIcon, LucideIcon> = {
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  rabbit: Rabbit,
  snail: Snail,
  bug: Bug,
  flame: Flame,
  zap: Zap,
  star: Star,
  moon: Moon,
  sun: Sun,
  heart: Heart,
  skull: Skull,
  ghost: Ghost,
  rocket: Rocket,
  crown: Crown,
  gem: Gem,
  anchor: Anchor,
  "gamepad-2": Gamepad2,
};

export const ICON_COLORS: string[] = [
  "bg-rose-500",
  "bg-orange-500",
  "bg-amber-500",
  "bg-yellow-500",
  "bg-lime-500",
  "bg-green-500",
  "bg-emerald-500",
  "bg-teal-500",
  "bg-cyan-500",
  "bg-sky-500",
  "bg-blue-500",
  "bg-indigo-500",
  "bg-violet-500",
  "bg-purple-500",
  "bg-fuchsia-500",
  "bg-pink-500",
  "bg-red-500",
  "bg-orange-600",
  "bg-teal-600",
  "bg-blue-600",
];
